### ISSUE TITLE
Is error detection too aggressive?

### ISSUE THREAD

**Issue by ckcrs** [SignalK/nmea0183-signalk#243]
I did not see why 3rd nmea0183-signalk error below.
I would expect if "" exists as input, not to be parsed anyway.
-----------------------
```
Mar 18 08:54:44 2023-03-18T05:54:44.095Z signalk:streams:nmea0183-signalk Error: Sentence "$STALK,00,02,60,5A,00*1A" is invalid at Parser.parse (/usr/lib/node_modules/signalk-server/node_modules/@signalk/nmea0183-signalk/lib/index.js:74:13) at Nmea0183ToSignalK._transform (/usr/lib/node_modules/signalk-server/node_modules/@signalk/streams/nmea0183-signalk.js:99:29) at Nmea0183ToSignalK.Transform._write (node:internal/streams/transform:205:23) at writeOrBuffer (node:internal/streams/writable:391:12) at _write (node:internal/streams/writable:332:10) at Nmea0183ToSignalK.Writable.write (node:internal/streams/writable:336:10) at Replacer.ondata (node:internal/streams/readable:754:22) at Replacer.emit (node:events:513:28) at addChunk (node:internal/streams/readable:315:12) at readableAddChunk (node:internal/streams/readable:289:9) at Replacer.Readable.push (node:internal/streams/readable:228:10) at Replacer._transform (/usr/lib/node_modules/signalk-server/node_modules/@signalk/streams/replacer.js:31:8) at Replacer.Transform._write (node:internal/streams/transform:205:23) at writeOrBuffer (node:internal/streams/writable:391:12) at _write (node:internal/streams/writable:332:10) at Replacer.Writable.write (node:internal/streams/writable:336:10)
Mar 18 08:54:46 [object Object]
Mar 18 08:54:47 Illegal value in delta:{"path":"navigation.courseOverGroundTrue"}
Mar 18 08:54:47 2023-03-18T05:54:47.192Z signalk:streams:nmea0183-signalk Error: Sentence "$STALK,84,26,14,00,40,$0,FF,00,06*62" is invalid at Parser.parse (/usr/lib/node_modules/signalk-server/node_modules/@signalk/nmea0183-signalk/lib/index.js:74:13) at Nmea0183ToSignalK._transform (/usr/lib/node_modules/signalk-server/node_modules/@signalk/streams/nmea0183-signalk.js:99:29) at Nmea0183ToSignalK.Transform._write (node:internal/streams/transform:205:23) at writeOrBuffer (node:internal/streams/writable:391:12) at _write (node:internal/streams/writable:332:10) at Nmea0183ToSignalK.Writable.write (node:internal/streams/writable:336:10) at Replacer.ondata (node:internal/streams/readable:754:22) at Replacer.emit (node:events:513:28) at addChunk (node:internal/streams/readable:315:12) at readableAddChunk (node:internal/streams/readable:289:9) at Replacer.Readable.push (node:internal/streams/readable:228:10) at Replacer._transform (/usr/lib/node_modules/signalk-server/node_modules/@signalk/streams/replacer.js:31:8) at Replacer.Transform._write (node:internal/streams/transform:205:23) at writeOrBuffer (node:internal/streams/writable:391:12) at _write (node:internal/streams/writable:332:10) at Replacer.Writable.write (node:internal/streams/writable:336:10)
Mar 18 08:54:51 [object Object]
Mar 18 08:54:52 2023-03-18T05:54:52.115Z signalk:streams:nmea0183-signalk Error: Sentence "" is invalid at Parser.parse (/usr/lib/node_modules/signalk-server/node_modules/@signalk/nmea0183-signalk/lib/index.js:74:13) at Nmea0183ToSignalK._transform (/usr/lib/node_modules/signalk-server/node_modules/@signalk/streams/nmea0183-signalk.js:99:29) at Nmea0183ToSignalK.Transform._write (node:internal/streams/transform:205:23) at writeOrBuffer (node:internal/streams/writable:391:12) at _write (node:internal/streams/writable:332:10) at Nmea0183ToSignalK.Writable.write (node:internal/streams/writable:336:10) at PigpioSeatalk.ondata (node:internal/streams/readable:754:22) at PigpioSeatalk.emit (node:events:513:28) at addChunk (node:internal/streams/readable:315:12) at readableAddChunk (node:internal/streams/readable:289:9) at PigpioSeatalk.Readable.push (node:internal/streams/readable:228:10) at Socket.<anonymous> (/usr/lib/node_modules/signalk-server/node_modules/@signalk/streams/execute.js:76:10) at Socket.emit (node:events:513:28) at addChunk (node:internal/streams/readable:315:12) at readableAddChunk (node:internal/streams/readable:289:9) at Socket.Readable.push (node:internal/streams/readable:228:10)
```

**Comment by tkurki** [comment]
Sorry, don't understand what you are trying to say here.

**Comment by ckcrs** [comment]
Since I did not get this with latest version of SK, I believe either already solved or I correct my mistake, unfortunately I do not remember any more detail. I
 think we may close this if you are aligned? Thanks.
